collections:
  projects:
    output : true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
        layout : project
        thumb : untitled.png
        name : untitled
        images : []
        download: []
        information : []
        description : short description

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
